{% set name = "dask-ee" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dask_ee-{{ version }}.tar.gz
  sha256: 86383caacd58cd20ce85c69357daff47a511396a00017e6b580670fa7751504a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - earthengine-api >=0.1.374
    - dask-core
    - pandas

test:
  imports:
    - dask_ee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alxmrs/dask-ee
  summary: Google Earth Engine FeatureCollections via Dask DataFrames.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/alxmrs/dask-ee

extra:
  recipe-maintainers:
    - alxmrs
    - giswqs
